set(ASM_DIALECT "_FASMG")
set(FASMG_ROOT_DIR "${CMAKE_SOURCE_DIR}/vendor/fasmg")
set(FASMG_WRAPPER_PATH "${CMAKE_SOURCE_DIR}/cmake/fasmg-wrapper.sh")
set(FASMG_INCLUDE "${FASMG_ROOT_DIR}/packages/x86/include")
set(CMAKE_ASM${ASM_DIALECT}_SOURCE_FILE_EXTENSIONS s;asm)

set(CMAKE_ASM${ASM_DIALECT}_COMPILE_OBJECT "${FASMG_WRAPPER_PATH} ${FASMG_INCLUDE} ${FASMG_ROOT_DIR}/core/fasmg.x64 <SOURCE> <OBJECT>")
#set(CMAKE_ASM${ASM_DIALECT}_COMPILE_OBJECT "<CMAKE_ASM${ASM_DIALECT}_COMPILER> <SOURCE> <OBJECT>")

include(CMakeASMInformation)
set(ASM_DIALECT)
